# onty-js-simpleExpressServer2
# .travis.yml
# by onTy


language: node_js

node_js:
  - "7"

#stages:
#  - myEnvtValidation
#  - myTest
#  - myPackage
#  - myDeploy
#
#jobs:
#  include:
#    - stage: envtValidation
#
#    - stage: test
#    - script: node --check bin/www app.js
#    - stage: myPackage
#    - script: zip -r --exclude=\*.git\* --exclude=\*node_modules\* buildPackaged.zip
#
#    - stage: deploy
#    - deploy: true

cache:
  directories:
    - "node_modules"




before_install:
  - script: echo 1_BEFORE_INSTALL
  - script: uname -a
  - script: whoami
  - script: pwd
  - script: echo $PATH
  - script: node --version
  - script: npm --version
  - script: node --check *.js

install:
  - script: echo 2_INSTALL
  - script: npm install

before_script:
  - script: echo 3_BEFORE_SCRIPT

script:
  - script: echo 4_SCRIPT

before_cache:   # OPTIONAL (for cleaning up cache)
  - script: echo 5_BEFORE_CACHE

#after_success or after_failure

before_deploy:  #opt
  - script: echo 6_BEFORE_DEPLOY
  - script: zip -r --exclude=\*.git\* --exclude=\*node_modules\* buildPackaged.zip

deploy:         #opt
  - script: echo 7_DEPLOY
  - provider:       elasticbeanstalk
  - access_key_id: "AKIAI3B37TG2YOSK4EMA"
  - secret_access_key:
      secure:       "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"
  - zip-file:       buildPackaged.zip
  - region:         "us-east-1"
  - app:            "onty-js-simpleExpressServer2"
  - env:            "onty-eb-env-SimpleExpressServer2"
  - bucket_name:    "onty-deployments-manual"

after_deploy:   #opt
  - script: echo 8_AFTER_DEPLOY

after_script:
  - script: echo 9_AFTER_SCRIPT



