# onty-js-simpleExpressServer2
# .travis.yml
# by onTy


language: node_js

node_js:
  - "7"

stages:
  - myEnvtValidation
  - myTest
  - myPackage
  - myDeploy

jobs:
  include:
    - stage: envtValidation
    - script: uname -a
    - script: whoami
    - script: pwd
    - script: echo $PATH
    - script: node --version
    - script: npm --version

    - stage: test
    - script: node --check bin/www app.js
    - stage: myPackage
    - script: zip -r --exclude=\*.git\* --exclude=\*node_modules\* buildPackaged.zip

    - stage: deploy
    - deploy: true

cache:
  directories:
    - "node_modules"




before_install:
install:
before_script:
script:
#before_cache OPTIONAL (for cleaning up cache)
#after_success or after_failure
before_deploy:  #opt
deploy:         #opt
  - provider:       elasticbeanstalk
  - access_key_id: "AKIAI3B37TG2YOSK4EMA"
  - secret_access_key:
    secure:       "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"
  - zip-file:       buildPackaged.zip
  - region:         "us-east-1"
  - app:            "onty-js-simpleExpressServer2"
  - env:            "onty-eb-env-SimpleExpressServer2"
  - bucket_name:    "onty-deployments-manual"

after_deploy:   #opt
after_deploy:   #opt
after_script:


deploy:
