# onty-js-simpleExpressServer2
# .travis.yml
# by onTy


language: node_js

node_js:
  - "7"

stages:
  - myTest
  - myDeploy

jobs:
  include:
    - stage: test
    - script: node --version
    - script: npm --version
    - stage: deploy

cache:
  directories:
    - "node_modules"


deploy:
  provider: elasticbeanstalk
  access_key_id: "AKIAI3B37TG2YOSK4EMA"
  secret_access_key:
    secure: "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"
  region: "us-east-1"
  app: "onty-js-simpleExpressServer2"
  env: "onty-eb-env-SimpleExpressServer2"
  bucket_name: "onty-deployments-manual"
