# onty-js-simpleExpressServer2
# .travis.yml
# by onTy


language: node_js

node_js:
  - "7"

#stages:
#  - myEnvtValidation
#  - myTest
#  - myPackage
#  - myDeploy
#
#jobs:
#  include:
#    - stage: envtValidation
#
#    - stage: test
#    - script: node --check bin/www app.js
#    - stage: myPackage
#    - script: zip -r buildPackaged.zip . --exclude=\*.git\* --exclude=\*node_modules\*
#
#    - stage: deploy
#    - deploy: true

cache:
  directories:
    - "node_modules"




before_install:
  - echo 1_BEFORE_INSTALL
  - uname -a
  - whoami
  - pwd
  - echo $PATH
  - node --version
  - npm --version
  - node --check *.js

install:
  - echo 2_INSTALL
  - npm install

before_script:
  - echo 3_BEFORE_SCRIPT
#  - rm -rf .git

script:
  - echo 4_SCRIPT

before_cache:   # OPTIONAL (for cleaning up cache)
  - echo 5_BEFORE_CACHE

#after_success or after_failure

before_deploy:  #opt
  - echo 6_BEFORE_DEPLOY
  - zip -r buildPackaged.zip . --exclude=\*.git\* --exclude=\*node_modules\*\
  - ls -la .

deploy:         #opt
#  - echo 7_DEPLOY
  provider:       elasticbeanstalk
  access_key_id: "AKIAI3B37TG2YOSK4EMA"
  secret_access_key:
    secure:       "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"
  zip-file:       buildPackaged.zip
  region:         "us-east-1"
  app:            "onty-js-simpleExpressServer2"
  env:            "onty-eb-env-SimpleExpressServer2"
  bucket_name:    "onty-deployments-manual"

after_deploy:   #opt
  - echo 8_AFTER_DEPLOY

after_script:
  - echo 9_AFTER_SCRIPT



